// ---Auto Generated by Only4Play ---
package com.example.achieve.vo.medal;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(
    chain = true
)
@JsonIgnoreProperties({ "handler" })
@ApiModel(
    value = "Medal对象",
    description = "勋章表Vo"
)
public class MedalVo {
  private long serialVersionUID;

  @ApiModelProperty("勋章id")
  @JsonProperty("id")
  private Integer id;

  @ApiModelProperty("勋章名称")
  @JsonProperty("name")
  private String name;

  @ApiModelProperty("展示图标")
  @JsonProperty("picture")
  private String picture;

  @ApiModelProperty("有效时限（天）（被领取后的有效时限）")
  @JsonProperty("time_limit")
  private Integer timeLimit;

  @ApiModelProperty("备注")
  @JsonProperty("tips")
  private String tips;

  @ApiModelProperty("激活时间（勋章被系统激活时间）")
  @JsonProperty("create_time")
  @JsonFormat(
      pattern = "yyyy-MM-dd HH:mm:ss",
      timezone = "GMT+8"
  )
  private Date createTime;

  @ApiModelProperty("类型 0个人 1房间 ")
  @JsonProperty("type1")
  private Integer type1;

  @ApiModelProperty("类型 0内部勋章 1守护者 2偶像明星 3room star 4 最受欢迎房 5cp守护者（男/女）6魅力勋章")
  @JsonProperty("type2")
  private Integer type2;

  @ApiModelProperty("成就类型 0荣誉（活动）勋章 1 成就勋章")
  @JsonProperty("achieve")
  private Integer achieve;

  @ApiModelProperty("0可领取 1不可领取")
  @JsonProperty("status")
  private Integer status;

  @ApiModelProperty("0展示 1不展示")
  @JsonProperty("show_status")
  private Integer showStatus;

  @ApiModelProperty("特效svga文件")
  @JsonProperty("special_effects")
  private String specialEffects;

  @ApiModelProperty("条件值（财富值）")
  @JsonProperty("condition_value")
  private Integer conditionValue;

  @ApiModelProperty("数字越小排名越靠前")
  @JsonProperty("sort")
  private Integer sort;

  @ApiModelProperty("1删除 0正常")
  @JsonProperty("is_del")
  private Integer isDel;
}
