// ---Auto Generated by Only4Play ---
package com.example.achieve.param.folder;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.lang.Integer;
import java.lang.String;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(
    chain = true
)
@JsonIgnoreProperties({ "handler" })
@ApiModel(
    value = "app_folder对象",
    description = "添加文件夹表Param"
)
public class AddAppFolderParam {
  private long serialVersionUID;

  @ApiModelProperty("文件夹id")
  @JsonProperty("app_folder_id")
  private Integer appFolderId;

  @ApiModelProperty("文件夹名称")
  @JsonProperty("app_folder_name")
  private String appFolderName;

  @ApiModelProperty("父文件夹id")
  @JsonProperty("app_folder_pid")
  private Integer appFolderPid;

  @ApiModelProperty("创建时间")
  @JsonProperty("create_time")
  private LocalDateTime createTime;
}
