// ---Auto Generated by Only4Play ---
package com.example.achieve.param.folder;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.lang.Integer;
import java.lang.String;
import java.time.LocalDateTime;
import javax.validation.constraints.NotBlank;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(
    chain = true
)
@JsonIgnoreProperties({ "handler" })
@ApiModel(
    value = "app_folder对象",
    description = "获取文件夹表Param"
)
public class GetListAppFolderParam {
  @ApiModelProperty("文件夹id")
  @JsonProperty("app_folder_id")
  @NotBlank(
      message = "文件夹id不能为空"
  )
  private Integer appFolderId;

  @ApiModelProperty("文件夹名称")
  @JsonProperty("app_folder_name")
  @NotBlank(
      message = "文件夹名称不能为空"
  )
  private String appFolderName;

  @ApiModelProperty("父文件夹id")
  @JsonProperty("app_folder_pid")
  @NotBlank(
      message = "父文件夹id不能为空"
  )
  private Integer appFolderPid;

  @ApiModelProperty("创建时间")
  @JsonProperty("create_time")
  @NotBlank(
      message = "创建时间不能为空"
  )
  private LocalDateTime createTime;
}
