// ---Auto Generated by Only4Play ---
package com.example.achieve.param.userAgent;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.lang.Integer;
import java.lang.String;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(
    chain = true
)
@JsonIgnoreProperties({ "handler" })
@ApiModel(
    value = "user_agent对象",
    description = "获取用户代理Param"
)
public class GetListUserAgentParam {
  @ApiModelProperty("当前页面")
  @JsonProperty("page")
  @NotNull(
      message = "当前页面不为空"
  )
  private int page;

  @ApiModelProperty("当前页面大小")
  @JsonProperty("limit")
  @NotNull(
      message = "当前页面大小不能空"
  )
  private int limit;

  @ApiModelProperty("用户代理表id")
  @JsonProperty("user_agent_id")
  @NotBlank(
      message = "用户代理表id不能为空"
  )
  private Integer userAgentId;

  @ApiModelProperty("用户id")
  @JsonProperty("user_id")
  @NotBlank(
      message = "用户id不能为空"
  )
  private Integer userId;

  @ApiModelProperty("用户代理列表\t")
  @JsonProperty("user_agent_list")
  @NotBlank(
      message = "用户代理列表\t不能为空"
  )
  private String userAgentList;
}
