// ---Auto Generated by Only4Play ---
package com.example.achieve.param.userAgent;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.lang.Integer;
import java.lang.String;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(
    chain = true
)
@JsonIgnoreProperties({ "handler" })
@ApiModel(
    value = "user_agent对象",
    description = "更新用户代理Param"
)
public class UpdateUserAgentParam {
  private long serialVersionUID;

  @ApiModelProperty("用户代理表id")
  @JsonProperty("user_agent_id")
  private Integer userAgentId;

  @ApiModelProperty("用户id")
  @JsonProperty("user_id")
  private Integer userId;

  @ApiModelProperty("用户代理列表\t")
  @JsonProperty("user_agent_list")
  private String userAgentList;
}
