// ---Auto Generated by Only4Play ---
package com.example.achieve.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(
    chain = true
)
@JsonIgnoreProperties({ "handler" })
@ApiModel(
    value = "File对象",
    description = "文件信息对象Vo"
)
public class FileVo {
  @ApiModelProperty("文件id")
  @JsonProperty("app_file_id")
  private Long appFileId;

  @ApiModelProperty("文件名称")
  @JsonProperty("name")
  private String name;

  @ApiModelProperty("文件md5名称")
  @JsonProperty("md5")
  private String md5;

  @ApiModelProperty("文件上传路径")
  @JsonProperty("path")
  private String path;

  @ApiModelProperty("文件上传路径")
  @JsonProperty("upload_time")
  @JsonFormat(
      pattern = "yyyy-MM-dd HH:mm:ss",
      timezone = "GMT+8"
  )
  private Date uploadTime;

  @ApiModelProperty("文件后缀名称")
  @JsonProperty("suffix")
  private String suffix;

  @ApiModelProperty("是否删除")
  @JsonProperty("is_delete")
  private Integer isDelete;
}
