// ---Auto Generated by Only4Play ---
package com.example.achieve.vo;

import io.swagger.annotations.ApiModelProperty;
import java.lang.Integer;
import java.lang.String;
import lombok.Data;

@Data
public class UserVo {
  @ApiModelProperty("serialVersionUID")
  private long serialVersionUID;

  @ApiModelProperty("id")
  private Integer id;

  @ApiModelProperty("password")
  private String password;

  @ApiModelProperty("age")
  private Integer age;
}
