// ---Auto Generated by Only4Play ---
package com.example.achieve.param.userRelation;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.lang.Integer;
import javax.validation.constraints.NotBlank;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(
    chain = true
)
@JsonIgnoreProperties({ "handler" })
@ApiModel(
    value = "user_relation对象",
    description = "获取用户关系表Param"
)
public class GetListUserRelationParam {
  @ApiModelProperty("用户id")
  @JsonProperty("user_id")
  @NotBlank(
      message = "用户id不能为空"
  )
  private Integer userId;

  @ApiModelProperty("所属代理用户pid")
  @JsonProperty("user_agent_pid")
  @NotBlank(
      message = "所属代理用户pid不能为空"
  )
  private Integer userAgentPid;
}
