// ---Auto Generated by Only4Play ---
package com.example.achieve.vo.userAsset;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(
    chain = true
)
@JsonIgnoreProperties({ "handler" })
@ApiModel(
    value = "user_asset对象",
    description = "用户资产表Vo"
)
public class UserAssetVo {
  private long serialVersionUID;

  @ApiModelProperty("id")
  @JsonProperty("id")
  private Integer id;

  @ApiModelProperty("用户ID")
  @JsonProperty("user_id")
  private Integer userId;

  @ApiModelProperty("金币数量（余量）")
  @JsonProperty("gold_coin")
  private Long goldCoin;

  @ApiModelProperty("银币数量（余量）")
  @JsonProperty("silver_coin")
  private Long silverCoin;

  @ApiModelProperty("钻石数量（余量）")
  @JsonProperty("diamond")
  private Long diamond;

  @ApiModelProperty("财富等级;默认为1级（15级才能申请靓号、25以上房间靓号和个人靓号一致）")
  @JsonProperty("wealth_level")
  private Integer wealthLevel;

  @ApiModelProperty("魅力等级;默认为1级")
  @JsonProperty("charisma_level")
  private Integer charismaLevel;

  @ApiModelProperty("财富值（金币）")
  @JsonProperty("wealth_val")
  private Long wealthVal;

  @ApiModelProperty("魅力值（金币）")
  @JsonProperty("charisma_val")
  private Long charismaVal;

  @ApiModelProperty("个人经验值")
  @JsonProperty("exp")
  private Integer exp;

  @ApiModelProperty("vip等级（默认为0 1-5vip可申请靓号ID）")
  @JsonProperty("vip_level")
  private Integer vipLevel;

  @ApiModelProperty("总充值人民币数额")
  @JsonProperty("RMB")
  private Long rmb;

  @ApiModelProperty("总充值美元数额")
  @JsonProperty("dollar")
  private Long dollar;

  @ApiModelProperty("代理充值")
  @JsonProperty("agent_recharge")
  private Long agentRecharge;

  @ApiModelProperty("贡献值（金币）")
  @JsonProperty("contribute")
  private Long contribute;

  @ApiModelProperty("钻石转金币的花费的总钻石数")
  @JsonProperty("diamond_gold")
  private Long diamondGold;

  @ApiModelProperty("本月收益（金币）")
  @JsonProperty("thismonth_earnings")
  private Long thismonthEarnings;

  @ApiModelProperty("上月收益（金币）")
  @JsonProperty("lastmonth_earnings")
  private Long lastmonthEarnings;

  @ApiModelProperty("用户等级（默认1级）")
  @JsonProperty("user_level")
  private Integer userLevel;

  @ApiModelProperty("1封禁消费 0正常")
  @JsonProperty("is_freeze")
  private Integer isFreeze;

  @ApiModelProperty("账户余额（美金）")
  @JsonProperty("balance")
  private Long balance;

  @ApiModelProperty("vip过期时间")
  @JsonProperty("vip_expire_time")
  private LocalDateTime vipExpireTime;

  @ApiModelProperty("装备的座驾ID")
  @JsonProperty("equip_ride")
  private Integer equipRide;

  @ApiModelProperty("装备的头像框ID")
  @JsonProperty("equip_avatar_box")
  private Integer equipAvatarBox;

  @ApiModelProperty("充值次数")
  @JsonProperty("recharge_count")
  private Integer rechargeCount;

  @ApiModelProperty("充值金币（充值数额转换成金币数）1美元:1000金币")
  @JsonProperty("recharge_gold")
  private String rechargeGold;
}
